### ISSUE TITLE
[get-all.sh] Script is cloning client/devel repositories in wrong path

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/bpm-sw-app#1]
After install all common dependecies (malamute, libzmq, libsodium and czmq), the script clones the bpm-sw-cli (for example) inside libzmq's folder. Therefore, it can't find the ./compile script.

**Comment by lerwys** [comment]
Fixed in commits 5a3efaba8655f7093c44dd45bc1b8828cacd2373 to 1d1ea422e1d0f8b8e6e59e44a39437d539d13bfd
